### ISSUE TITLE
S-101.2 Simulations of estimating admixture fractions from individuals simulated from estimated allele frequencies

### ISSUE THREAD

**Issue by eriqande** [eriqande/gscramble-paper-sims-and-analyses#3]

**Comment by tjsmyser** [comment]
It would be interesting to explore this over a range of markers to illustrate that as the number of genetic markers increases so too does the likelihood of type 1 error of identifying genetic structure when there is none.

**Comment by eriqande** [comment]
I have pretty much done this.
